//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int pID { get; set; }
        public string playerNAME { get; set; }
        public Nullable<int> playerPUNKTE { get; set; }
    }
}
